version: 0.2
phases:
  pre_build:
    commands:
      - LIB=${APP_PATH}/lib
      - if [ -d ${LIB} ]; then rm -r ${LIB}; fi
      - mkdir -p ${LIB}
      - pip3 install --target ${LIB} urllib3
  build:
    commands:
      - cd ${LIB} && zip -gr9 ${OLDPWD}/${PKG} .
      - cd ${OLDPWD}
      - SRC=${APP_PATH}
      - cd ${SRC} && zip ${OLDPWD}/${PKG} *.py
      - cd ${OLDPWD}
  post_build:
    commands:
      - aws s3 cp ${PKG} s3://${ARTIFACT_BUCKET}/
artifacts:
  files: ${PKG}
